// ✅ CORRECTED: Proper Singleton implementation with Hive support
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../../data/models/task_model.dart';
import '../constants/app_constants.dart';
import '../../data/models/user_model.dart';
import '../constants/enums.dart'; // ✨ Import for adapter

/// Singleton service for managing all storage operations
///
/// Handles three types of storage:
/// 1. Secure Storage - For sensitive data (passwords, tokens)
/// 2. Shared Preferences - For app settings
/// 3. Hive Database - For offline data (users, tasks)
///
/// Usage:
/// ```dart
/// final storage = StorageService();
/// await storage.saveSecure('token', 'abc123');
/// final token = await storage.readSecure('token');
/// ```
class StorageService {
  // ============================================================================
  // SINGLETON PATTERN
  // ============================================================================

  /// Single instance of StorageService
  static final StorageService _instance = StorageService._internal();

  /// Factory constructor returns the same instance
  factory StorageService() => _instance;

  /// Private constructor (called only once)
  StorageService._internal();

  // ============================================================================
  // STORAGE INSTANCES
  // ============================================================================

  late final FlutterSecureStorage _secureStorage;
  late final SharedPreferences _prefs;
  bool _initialized = false;
  Box<TaskModel>? _taskBox;
  String? _currentUid;

  // ============================================================================
  // INITIALIZATION
  // ============================================================================

  /// Initialize all storage systems
  ///
  /// Must be called before using any storage methods
  /// Safe to call multiple times (initializes only once)
  ///
  /// Call this in main.dart before runApp():
  /// ```dart
  /// await StorageService().initialize();
  /// ```
  Future<void> initialize() async {
    // Prevent multiple initializations
    if (_initialized) return;

    try {
      // ========================================================================
      // 1. Initialize Hive
      // ========================================================================
      await Hive.initFlutter();

      // ========================================================================
      // 2. Register Hive Type Adapters
      // ========================================================================
      // UserModelAdapter is generated by build_runner
      // Only register if not already registered
      if (!Hive.isAdapterRegistered(0)) {
        Hive.registerAdapter(UserModelAdapter());
      }

      // TODO: Register more adapters as you create them
      if (!Hive.isAdapterRegistered(1)) {
        Hive.registerAdapter(TaskModelAdapter());
      }

      if (!Hive.isAdapterRegistered(2)) {
        Hive.registerAdapter(TaskPriorityAdapter());
      }

      if (!Hive.isAdapterRegistered(3)) {
        Hive.registerAdapter(TaskCategoryAdapter());
      }

      // ========================================================================
      // 3. Open Hive Boxes
      // ========================================================================
      // Open boxes so they're ready to use
      await Hive.openBox<UserModel>(AppConstants.userBox);
      // await Hive.openBox<TaskModel>(AppConstants.taskBox);
      await Hive.openBox(AppConstants.settingsBox);

      // ========================================================================
      // 4. Initialize Secure Storage
      // ========================================================================
      _secureStorage = const FlutterSecureStorage(
        aOptions: AndroidOptions(encryptedSharedPreferences: true),
        iOptions: IOSOptions(accessibility: KeychainAccessibility.first_unlock),
      );

      // ========================================================================
      // 5. Initialize Shared Preferences
      // ========================================================================
      _prefs = await SharedPreferences.getInstance();

      _initialized = true;
      print('✅ StorageService initialized successfully');
    } catch (e) {
      print('❌ StorageService initialization failed: $e');
      rethrow;
    }
  }

  /// Check if storage is initialized
  bool get isInitialized => _initialized;

  // ============================================================================
  // SECURE STORAGE METHODS (For sensitive data like passwords, tokens)
  // ============================================================================

  /// Save data securely (encrypted)
  ///
  /// Example:
  /// ```dart
  /// await storage.saveSecure('password', 'myPassword123');
  /// ```
  Future<void> saveSecure(String key, String value) async {
    await _secureStorage.write(key: key, value: value);
  }

  /// Read secure data
  ///
  /// Example:
  /// ```dart
  /// final password = await storage.readSecure('password');
  /// ```
  Future<String?> readSecure(String key) async {
    return await _secureStorage.read(key: key);
  }

  /// Delete secure data
  Future<void> deleteSecure(String key) async {
    await _secureStorage.delete(key: key);
  }

  /// Delete all secure data
  Future<void> deleteAllSecure() async {
    await _secureStorage.deleteAll();
  }

  /// Read all secure data
  Future<Map<String, String>> readAllSecure() async {
    return await _secureStorage.readAll();
  }

  // ============================================================================
  // SHARED PREFERENCES METHODS (For app settings)
  // ============================================================================

  /// Save boolean value
  Future<bool> saveBool(String key, bool value) async {
    return await _prefs.setBool(key, value);
  }

  /// Read boolean value
  bool? readBool(String key) {
    return _prefs.getBool(key);
  }

  /// Save string value
  Future<bool> saveString(String key, String value) async {
    return await _prefs.setString(key, value);
  }

  /// Read string value
  String? readString(String key) {
    return _prefs.getString(key);
  }

  /// Save integer value
  Future<bool> saveInt(String key, int value) async {
    return await _prefs.setInt(key, value);
  }

  /// Read integer value
  int? readInt(String key) {
    return _prefs.getInt(key);
  }

  /// Save double value
  Future<bool> saveDouble(String key, double value) async {
    return await _prefs.setDouble(key, value);
  }

  /// Read double value
  double? readDouble(String key) {
    return _prefs.getDouble(key);
  }

  /// Save string list
  Future<bool> saveStringList(String key, List<String> value) async {
    return await _prefs.setStringList(key, value);
  }

  /// Read string list
  List<String>? readStringList(String key) {
    return _prefs.getStringList(key);
  }

  /// Remove a key from SharedPreferences
  Future<bool> remove(String key) async {
    return await _prefs.remove(key);
  }

  /// Clear all SharedPreferences
  Future<bool> clear() async {
    return await _prefs.clear();
  }

  /// Check if key exists in SharedPreferences
  bool containsKey(String key) {
    return _prefs.containsKey(key);
  }

  // ============================================================================
  // HIVE METHODS (For offline database)
  // ============================================================================

  /// Get a Hive box by name
  ///
  /// Example:
  /// ```dart
  /// final userBox = storage.getBox(AppConstants.userBox);
  /// await userBox.put('user1', userModel);
  /// ```
  Box getBox(String boxName) {
    return Hive.box(boxName);
  }

  /// Get a typed Hive box
  ///
  /// Example:
  /// ```dart
  /// final userBox = storage.getTypedBox<UserModel>(AppConstants.userBox);
  /// ```
  Box<T> getTypedBox<T>(String boxName) {
    return Hive.box<T>(boxName);
  }

  /// Save user to Hive
  ///
  /// Helper method for common operation
  Future<void> saveUser(UserModel user) async {
    final box = getTypedBox<UserModel>(AppConstants.userBox);
    await box.put(user.uid, user);
  }

  /// Get user from Hive
  ///
  /// Returns null if user not found
  UserModel? getUser(String uid) {
    final box = getTypedBox<UserModel>(AppConstants.userBox);
    return box.get(uid);
  }

  /// Get current user (first user in box)
  ///
  /// Useful for single-user apps
  UserModel? getCurrentUser() {
    final box = getTypedBox<UserModel>(AppConstants.userBox);
    if (box.isEmpty) return null;
    return box.getAt(0);
  }

  /// Delete user from Hive
  Future<void> deleteUser(String uid) async {
    final box = getTypedBox<UserModel>(AppConstants.userBox);
    await box.delete(uid);
  }

  /// Clear all data from a specific box
  Future<void> clearBox(String boxName) async {
    final box = getBox(boxName);
    await box.clear();
  }

  /// Close all Hive boxes
  Future<void> closeHive() async {
    await Hive.close();
  }

  /// Called AFTER login success
  Future<void> openUserBoxes(String uid) async {
    if (_currentUid == uid && _taskBox != null) return;

    // Close previous user's box if exists
    if (_taskBox != null && _taskBox!.isOpen) {
      await _taskBox!.close();
    }

    final name = "${AppConstants.taskBox}_$uid";

    if (!Hive.isBoxOpen(name)) {
      _taskBox = await Hive.openBox<TaskModel>(name);
    } else {
      _taskBox = Hive.box<TaskModel>(name);
    }

    _currentUid = uid;
  }

  /// Called on logout
  Future<void> closeUserBoxes() async {
    await _taskBox?.close();
    _taskBox = null;
    _currentUid = null;
  }

  // ============================================================================
  // COMBINED CLEAR METHOD
  // ============================================================================

  /// Clear all storage (secure, prefs, and Hive)
  ///
  /// Use with caution - this deletes everything!
  /// Useful for logout or reset functionality
  Future<void> clearAll() async {
    try {
      await _secureStorage.deleteAll();
      await _prefs.clear();
      await Hive.box(AppConstants.userBox).clear();
      if (_taskBox != null && _taskBox!.isOpen) {
        await _taskBox!.clear();
      }
      await Hive.box(AppConstants.settingsBox).clear();
    } catch (e) {
      print('⚠️ clearAll encountered an error: $e');
    }
  }
}
